const FLAGS: Record<string, string> = {
  'Meksyk':                        '🇲🇽',
  'Korea Południowa':               '🇰🇷',
  'Czechy':                         '🇨🇿',
  'RPA':                            '🇿🇦',
  'Kanada':                         '🇨🇦',
  'Bośnia i Hercegowina':           '🇧🇦',
  'Katar':                          '🇶🇦',
  'Szwajcaria':                     '🇨🇭',
  'Brazylia':                       '🇧🇷',
  'Maroko':                         '🇲🇦',
  'Haiti':                          '🇭🇹',
  'Szkocja':                        '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Stany Zjednoczone':              '🇺🇸',
  'Australia':                      '🇦🇺',
  'Turcja':                         '🇹🇷',
  'Paragwaj':                       '🇵🇾',
  'Niemcy':                         '🇩🇪',
  'Ekwador':                        '🇪🇨',
  'Wybrzeże Kości Słoniowej':       '🇨🇮',
  'Curaçao':                        '🇨🇼',
  'Holandia':                       '🇳🇱',
  'Japonia':                        '🇯🇵',
  'Szwecja':                        '🇸🇪',
  'Tunezja':                        '🇹🇳',
  'Belgia':                         '🇧🇪',
  'Egipt':                          '🇪🇬',
  'Iran':                           '🇮🇷',
  'Nowa Zelandia':                  '🇳🇿',
  'Hiszpania':                      '🇪🇸',
  'Wyspy Zielonego Przylądka':      '🇨🇻',
  'Arabia Saudyjska':               '🇸🇦',
  'Urugwaj':                        '🇺🇾',
  'Francja':                        '🇫🇷',
  'Senegal':                        '🇸🇳',
  'Irak':                           '🇮🇶',
  'Norwegia':                       '🇳🇴',
  'Argentyna':                      '🇦🇷',
  'Algieria':                       '🇩🇿',
  'Austria':                        '🇦🇹',
  'Jordania':                       '🇯🇴',
  'Portugalia':                     '🇵🇹',
  'DR Kongo':                       '🇨🇩',
  'Uzbekistan':                     '🇺🇿',
  'Kolumbia':                       '🇨🇴',
  'Anglia':                         '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Chorwacja':                      '🇭🇷',
  'Ghana':                          '🇬🇭',
  'Panama':                         '🇵🇦',
}

export function flag(teamName: string): string {
  return FLAGS[teamName] ?? '🏳'
}
